#!/bin/bash

#
# Sets up $WWW_ROOT as a volume owned by $LAPP_WWW_OWNER
# ======================================================
#

set -e

. /usr/local/lib/utils.inc
. /usr/local/lib/env.inc

# Load the runtime environment
load_env

# Set up $WWW_ROOT as a volume (bind-mounted or unbound)
setup_volume $WWW_ROOT $APACHE_USER "$LAPP_WWW_OWNER"

log_info "LAPP container image tags: $DEPLOY_TAGS (created on $(date --reference ${WWW_ROOT} --rfc-2822))"
