#!/bin/bash

#
# Configures PHP and XDebug
# =========================
#

set -e

. /usr/local/lib/utils.inc
. /usr/local/lib/env.inc

# Load the runtime environment
load_env

# Select developer/XDebug/production mode, accept abbreviations and ignore case
while true; do
    if [[ -n $MODE && dev == ${MODE,,}* ]]; then
        log_info 'Apache/PHP in developer mode'
        set_var MODE dev
        EXT=dev
        XDEBUG=
        break
    fi

    if [[ -n $MODE && xdebug == ${MODE,,}* ]]; then
        log_info 'Apache/PHP in developer mode with XDebug support'
        set_var MODE xdebug
        EXT=dev
        XDEBUG=y
        break
    fi

    if [[ -z $MODE || prod == ${MODE,,}* ]]; then
        log_info 'Apache/PHP in production mode'
        set_var MODE prod
        EXT=prod
        XDEBUG=
        break
    fi

    err_exit "Unknown mode: '$MODE'"
done

# Update the Apache/PHP configuration
ln -sf /etc/apache2/conf.d/mode.conf.${EXT} /etc/apache2/conf.d/zz_mode.conf
ln -sf /etc/php/mode.${EXT}.template /etc/php${MAJOR_VERSION}/conf.d/zz_50_mode.ini

# Insert php.ini setting overrides
printenv \
    | awk -F '=' \
        -e 'BEGIN { IGNORECASE = 1 }' \
        -e '$1 ~ /^PHP_/ { gsub("^PHP_", "", $1); gsub(/"/, "\\\"", $2); printf "%s=\"%s\"\n", $1, $2; }' \
    > /etc/php${MAJOR_VERSION}/conf.d/zz_99_overrides.ini

if [ -s /etc/php${MAJOR_VERSION}/conf.d/zz_99_overrides.ini ]; then
    while read -r LINE; do
    	log_info "php.ini override: $LINE"
    done </etc/php${MAJOR_VERSION}/conf.d/zz_99_overrides.ini
fi

# Enable/disable XDebug support
if [ -n "$XDEBUG" ]; then
    # Connect back only if host IP not specified
    export REMOTE_HOST=$HOST_IP
    test -n "$HOST_IP" && set_var REMOTE_CONNECT_BACK 0 || set_var REMOTE_CONNECT_BACK 1

	cat /etc/php/xdebug.ini.template | envsubst > /etc/php${MAJOR_VERSION}/conf.d/xdebug.ini
	log_info "XDebug enabled"
    while read -r LINE; do
        log_info "php.ini XDebug: $LINE"
    done < <(grep -E '^xdebug\.(discover_)?client_host=' /etc/php${MAJOR_VERSION}/conf.d/xdebug.ini)

else
	truncate -s 0 /etc/php${MAJOR_VERSION}/conf.d/xdebug.ini
	log_info "XDebug disabled"
fi

php --version | log_info
