#!/bin/bash

#
# Sets up PostgreSQL with the requested configuration
# ===================================================
#

set -e

. /usr/local/lib/utils.inc
. /usr/local/lib/env.inc

# Load the runtime environment
load_env

# Set up $PG_DATA as a volume (bind-mounted or unbound)
setup_volume $PG_DATA $PG_USER "$LAPP_PG_OWNER"
chmod 700 $PG_DATA

mkdir -p $PG_RUN
chown -R $PG_USER: $PG_RUN

# Initialize PostgreSQL if necessary
if [ ! -f $PG_DATA/PG_VERSION ]; then
    # Initialize PostgreSQL
    PWFILE=$(mktemp -u)
    trap "shred -un 1 $PWFILE" EXIT

    # Create a random password if none was given
    if [ -z "$PG_PASSWORD" ]; then
        PG_PASSWORD=$(pwgen -cnB 12 1)
        log_info "Random password '$PG_PASSWORD' generated for PostgreSQL user '$PG_USER'. Change ASAP!"
    fi

    echo "$PG_PASSWORD" >$PWFILE
    su-exec $PG_USER \
    initdb --pgdata=$PG_DATA --auth=md5 --username=$PG_USER --pwfile=$PWFILE | log_info

    # Allow external IPv4 and IPv6 connections
    cat >>$PG_DATA/pg_hba.conf <<EOT

host  all  all  0.0.0.0/0  md5
host  all  all  ::0/0      md5
EOT
fi
